// Star generator for background
function createStars() {
    const starsContainer = document.getElementById('stars');
    const starCount = 150;

    for (let i = 0; i < starCount; i++) {
        const star = document.createElement('div');
        star.className = 'star';
        
        const size = Math.random() * 3 + 'px';
        star.style.width = size;
        star.style.height = size;
        
        star.style.left = Math.random() * 100 + '%';
        star.style.top = Math.random() * 100 + '%';
        
        star.style.setProperty('--duration', (Math.random() * 3 + 2) + 's');
        star.style.animationDelay = Math.random() * 5 + 's';
        
        starsContainer.appendChild(star);
    }
}

document.addEventListener('DOMContentLoaded', () => {
    createStars();

    const form = document.getElementById('astrolabe-form');
    const submitBtn = document.getElementById('submit-btn');
    const btnText = submitBtn.querySelector('.btn-text');
    const loader = document.getElementById('loader');
    const resultContainer = document.getElementById('result-container');
    const reportLink = document.getElementById('report-link');

    form.addEventListener('submit', async (e) => {
        e.preventDefault();

        // UI Feedback
        btnText.style.opacity = '0';
        loader.style.display = 'block';
        submitBtn.disabled = true;
        resultContainer.classList.add('hidden');

        // Collect Data
        const name = document.getElementById('name').value;
        const location = document.getElementById('location').value;
        const dateRaw = document.getElementById('birth-date').value; // YYYY-MM-DD
        const timeRaw = document.getElementById('birth-time').value; // HH:MM

        // Format to YYYY-MMDD-HHMM
        const [year, month, day] = dateRaw.split('-');
        const [hour, minute] = timeRaw.split(':');
        const dobFormatted = `${year}-${month}${day}-${hour}${minute}`;

        try {
            const response = await fetch('/calculate', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    name: name,
                    location: location,
                    dob: dobFormatted
                })
            });

            const result = await response.json();

            if (response.ok) {
                // In a real app, the server would return a URL or HTML.
                // For this demo, let's assume we generated a file report_{name}.html
                // We'll tell the user to check their folder or provide a link if the server serves it.
                btnText.style.opacity = '1';
                loader.style.display = 'none';
                submitBtn.disabled = false;

                resultContainer.classList.remove('hidden');
                // The filename generated by main.py is report_{NAME}.html in the logic folder?
                // Actually the current app.py doesn't generate the file yet, it just returns JSON.
                // Let's modify app.py later to actually generate the report or return the HTML.
                
                // For now, let's just show success.
                reportLink.textContent = `View Report for ${name}`;
                // We'll need to serve the reports folder or similar.
                // Let's just point to where it usually is.
                reportLink.href = `/results/report_${name.toUpperCase()}.html`;
            } else {
                alert('Error: ' + (result.error || 'Failed to calculate'));
                btnText.style.opacity = '1';
                loader.style.display = 'none';
                submitBtn.disabled = false;
            }
        } catch (error) {
            console.error('Fetch error:', error);
            alert('An error occurred during calculation.');
            btnText.style.opacity = '1';
            loader.style.display = 'none';
            submitBtn.disabled = false;
        }
    });
});
