FIXED_STARS_DATA = [
    # ARIES
    {"name": "Kerb", "ra": "23h 20m 38s", "dec": "+23° 44' 25\"", "meaning": "Danger of being jilted; wildness."},
    {"name": "Difda (Deneb Kaitos)", "ra": "00h 43m 35s", "dec": "-17° 59' 12\"", "meaning": "Self-destruction, laziness, and nervousness."},
    {"name": "Algenib", "ra": "00h 13m 14s", "dec": "+15° 11' 01\"", "meaning": "Ambition, vanity, and quick mind."},
    {"name": "Alderamin", "ra": "21h 18m 34s", "dec": "+62° 35' 08\"", "meaning": "Gentle authority, dignity, and trial."},
    {"name": "Alpheratz", "ra": "00h 08m 23s", "dec": "+29° 05' 25\"", "meaning": "Grace, popularity, and independence."},
    {"name": "Baten Kaitos", "ra": "01h 51m 41s", "dec": "-10° 20' 06\"", "meaning": "Isolation, depression, and accidents."},
    {"name": "Acamar", "ra": "02h 58m 15s", "dec": "-40° 18' 17\"", "meaning": "Success in public office and high positions."},
    {"name": "Alrisha", "ra": "02h 02m 02s", "dec": "+02° 45' 49\"", "meaning": "Unifying influence and artistic talent."},
    
    # TAURUS
    {"name": "Mirach", "ra": "01h 09m 43s", "dec": "+35° 37' 14\"", "meaning": "Good fortune through marriage; beauty."},
    {"name": "Sharatan", "ra": "01h 54m 38s", "dec": "+20° 48' 28\"", "meaning": "Violence, defeat, and accidents."},
    {"name": "Hamal", "ra": "02h 07m 10s", "dec": "+23° 27' 44\"", "meaning": "Headstrong, independent, and aggressive."},
    {"name": "Schedir", "ra": "00h 40m 30s", "dec": "+56° 32' 14\"", "meaning": "Female dignity, intuition, and power."},
    {"name": "Almach", "ra": "02h 03m 53s", "dec": "+42° 19' 47\"", "meaning": "Success in arts and social status."},
    {"name": "Menkar", "ra": "03h 02m 16s", "dec": "+04° 05' 23\"", "meaning": "Turbulence, illness, and loss of fortune."},
    {"name": "Rana", "ra": "03h 43m 14s", "dec": "-09° 45' 48\"", "meaning": "Knowledge, love of science, and quiet life."},
    {"name": "Algol", "ra": "03h 08m 10s", "dec": "+40° 57' 20\"", "meaning": "Most evil star; violence, intensity, danger."},
    {"name": "Zaurak", "ra": "03h 54m 17s", "dec": "-13° 30' 33\"", "meaning": "Melancholy, fear of death, and long-term worry."},
    {"name": "Caput Algol", "ra": "03h 08m 10s", "dec": "+40° 57' 20\"", "meaning": "Extreme misfortune, violence, and intense passion."},
    {"name": "Pleiades", "ra": "03h 47m 24s", "dec": "+24° 07' 00\"", "meaning": "Sensitivity, blindness (metaphorical), and group influence."},
    
    # GEMINI
    {"name": "Alcyone", "ra": "03h 47m 29s", "dec": "+24° 06' 18\"", "meaning": "Ambition, honor, but potential for bereavement."},
    {"name": "Hyades", "ra": "04h 28m 17s", "dec": "+15° 52' 00\"", "meaning": "Emotionality, pressure, and sudden events."},
    {"name": "Aldebaran", "ra": "04h 35m 55s", "dec": "+16° 30' 33\"", "meaning": "Great success and honor, but danger of integrity loss."},
    {"name": "Cursa", "ra": "05h 07m 51s", "dec": "-05° 05' 11\"", "meaning": "Sudden changes of position, academic success."},
    {"name": "Rigel", "ra": "05h 14m 32s", "dec": "-08° 12' 06\"", "meaning": "Riches, honors, and inventive mental ability."},
    {"name": "Bellatrix", "ra": "05h 25m 08s", "dec": "+06° 20' 59\"", "meaning": "Military honor, courage, but potential for sudden ruin."},
    {"name": "Capella", "ra": "05h 16m 41s", "dec": "+45° 59' 53\"", "meaning": "Love of learning, inquisitiveness, and civic honor."},
    {"name": "Phact", "ra": "05h 39m 39s", "dec": "-34° 04' 27\"", "meaning": "Good fortune, interest in science and art."},
    {"name": "El Nath", "ra": "05h 26m 17s", "dec": "+28° 36' 27\"", "meaning": "Success in business and high position."},
    {"name": "Alnilam", "ra": "05h 36m 13s", "dec": "-01° 12' 07\"", "meaning": "Fleet-footed fame, lasting honors, public role."},
    {"name": "Al Hecka", "ra": "05h 37m 39s", "dec": "+21° 08' 33\"", "meaning": "Violent nature, but potential for great success."},
    {"name": "Polaris", "ra": "02h 31m 49s", "dec": "+89° 15' 51\"", "meaning": "Guidance, path-finding, and potential for sickness."},
    {"name": "Betelgeuse", "ra": "05h 55m 10s", "dec": "+07° 24' 25\"", "meaning": "Great fortune, fame, and martial honor."},

    # Cancer
    {"name": "Propus", "ra": "06h 14m 52s", "dec": "+22° 30' 24\"", "meaning": "Success in eminent position, pride, and strength."},
    {"name": "Alhena", "ra": "06h 37m 43s", "dec": "+16° 23' 57\"", "meaning": "Artistic talent, spiritual orientation, and distinction in feet/walking."},
    {"name": "Alzirr", "ra": "06h 44m 37s", "dec": "+12° 54' 34\"", "meaning": "Hunting, sudden wealth, but vulnerability to setbacks."},
    {"name": "Sirius", "ra": "06h 45m 09s", "dec": "-16° 42' 58\"", "meaning": "Great brilliance, guardianship, wealth, and spiritual power."},
    {"name": "Canopus", "ra": "06h 23m 57s", "dec": "-52° 41' 44\"", "meaning": "Knowledge, travel, and changing of the old for the new."},
    {"name": "Castor", "ra": "07h 34m 36s", "dec": "+31° 53' 18\"", "meaning": "Intellect, sudden fame, but tendency towards sharp wit or injury."},
    {"name": "Pollux", "ra": "07h 45m 19s", "dec": "+28° 01' 34\"", "meaning": "Courage, audacity, but also potential for violence or cruelty."},
    {"name": "Procyon", "ra": "07h 39m 18s", "dec": "+05° 13' 30\"", "meaning": "Sudden success that may not last, activity, and impulsiveness."},

    # LEO
    {"name": "Talitha", "ra": "08h 59m 12s", "dec": "+48° 02' 30\"", "meaning": "Discretion, prudence, but potential for skepticism."},
    {"name": "Praesaepe", "ra": "08h 40m 22s", "dec": "+19° 40' 00\"", "meaning": "Sensitivity, blindness (metaphorical), and group business."},
    {"name": "North Asellus", "ra": "08h 43m 17s", "dec": "+21° 28' 00\"", "meaning": "Patience, beneficence, and courage."},
    {"name": "South Asellus", "ra": "08h 44m 41s", "dec": "+18° 09' 15\"", "meaning": "Defiance, aggression, and intense passion."},
    {"name": "Giansar", "ra": "12h 53m 23s", "dec": "+69° 19' 48\"", "meaning": "Analytical mind, craftiness, and protection."},
    {"name": "Acubens", "ra": "08h 58m 29s", "dec": "+11° 51' 28\"", "meaning": "Activity, sharpness, and potential for malice."},
    {"name": "Dubhe", "ra": "11h 03m 43s", "dec": "+61° 45' 03\"", "meaning": "Strength, persistence, and psychic ability."},
    {"name": "Merak", "ra": "11h 01m 50s", "dec": "+56° 22' 56\"", "meaning": "Prudence, caution, and love of command."},
    {"name": "Algenubi", "ra": "09h 45m 51s", "dec": "+23° 46' 27\"", "meaning": "Coldness, heartlessness, but great artistic appreciation."},
    {"name": "Alphard", "ra": "09h 27m 35s", "dec": "-08° 39' 31\"", "meaning": "Wisdom, musical talent, but potential for immorality or poisoning."},
    {"name": "Adhafera", "ra": "10h 16m 41s", "dec": "+23° 25' 02\"", "meaning": "Commanding presence, but associated with theft or deception."},
    {"name": "Al Jabhah", "ra": "10h 16m 41s", "dec": "+23° 25' 02\"", "meaning": "Intelligence, self-control, and military honor."},
    {"name": "Regulus", "ra": "10h 08m 22s", "dec": "+11° 58' 02\"", "meaning": "Royal honor, great success, leadership, but danger of revenge."},

    # VIRGO
    {"name": "Praecipua", "ra": "10h 53m 18s", "dec": "+34° 12' 53\"", "meaning": "Generous spirit, leadership, but potential for sudden changes."},
    {"name": "Thuban", "ra": "14h 04m 23s", "dec": "+64° 22' 33\"", "meaning": "Analytical mind, treasure-guarding, and spiritual searching."},
    {"name": "Zosma", "ra": "11h 14m 06s", "dec": "+20° 31' 25\"", "meaning": "Melancholy, suffering, but potential for prophetic ability."},
    {"name": "Mizar", "ra": "13h 23m 55s", "dec": "+54° 55' 31\"", "meaning": "Sharp mind, artistic talent, and connected to communal fate."},
    {"name": "Denebola", "ra": "11h 49m 03s", "dec": "+14° 34' 19\"", "meaning": "Nobility, daring, but potential for public disgrace or judgment."},
    {"name": "Coma Berenices", "ra": "12h 35m 00s", "dec": "+26° 00' 00\"", "meaning": "Sacrifice for love, charm, and great personal beauty."},
    {"name": "Labrum", "ra": "11h 13m 20s", "dec": "-17° 59' 12\"", "meaning": "Ideality, psychic power, and honor through communication."},
    {"name": "Alkaid", "ra": "13h 47m 32s", "dec": "+49° 18' 48\"", "meaning": "Association with death, mourning, and massive social shifts."},
    {"name": "Markeb", "ra": "09h 22m 06s", "dec": "-55° 00' 43\"", "meaning": "Knowledge, educational success, and steady voyages."},

    #Libra
    {"name": "Zaniah", "ra": "12h 07m 43s", "dec": "-00° 40' 01\"", "meaning": "Refinement, honor, and orderliness in relationships."},
    {"name": "Vindemiatrix", "ra": "13h 02m 11s", "dec": "+10° 57' 33\"", "meaning": "Falsity, folly, but also mental concentration and focus."},
    {"name": "Algorab", "ra": "12h 29m 52s", "dec": "-16° 30' 52\"", "meaning": "Destructive, craftiness, and potential for obstacles."},
    {"name": "Merga", "ra": "15h 15m 31s", "dec": "+19° 06' 05\"", "meaning": "Research-oriented, secretive, and analytical mind."},
    {"name": "Seginus", "ra": "14h 32m 05s", "dec": "+38° 18' 30\"", "meaning": "Mental brilliance, success through patience, but potential for loss through friends."},
    {"name": "Mufrid", "ra": "13h 54m 41s", "dec": "+18° 23' 52\"", "meaning": "Benevolence, interest in occult/philosophy, and prosperity."},
    {"name": "Foramen", "ra": "10h 45m 04s", "dec": "-59° 41' 04\"", "meaning": "Prosperity through leadership, but danger to eyesight/health."},
    {"name": "Spica", "ra": "13h 25m 12s", "dec": "-11° 09' 41\"", "meaning": "Unbounded good fortune, spiritual and artistic success, high honors."},
    {"name": "Arcturus", "ra": "14h 15m 39s", "dec": "+19° 10' 56\"", "meaning": "Great renown through self-determination, path-finding, and wealth."},

    # Scorpio
    {"name": "Princeps", "ra": "15h 27m 49s", "dec": "+19° 10' 54\"", "meaning": "Keen intellect, research ability, and success in specialized fields."},
    {"name": "Khambalia", "ra": "14h 14m 23s", "dec": "-18° 41' 30\"", "meaning": "Deep penetration, research into secrets, and sharp judgment."},
    {"name": "Acrux", "ra": "12h 26m 36s", "dec": "-63° 05' 57\"", "meaning": "Religious nature, interest in mystery, and ceremonial justice."},
    {"name": "Alphecca", "ra": "15h 34m 41s", "dec": "+26° 42' 53\"", "meaning": "Artistic talent, dignity, and success in trade or public life."},
    {"name": "Menken", "ra": "14h 06m 41s", "dec": "-36° 22' 11\"", "meaning": "Instruction, wisdom, and potential for high social position."},
    {"name": "Zuben Algenubi", "ra": "14h 50m 53s", "dec": "-16° 02' 30\"", "meaning": "Loss, theft, and obstacles (The 'South Scale')."},
    {"name": "Serpentis", "ra": "15h 44m 16s", "dec": "+06° 25' 32\"", "meaning": "Malice, cunning, and danger of poisoning or betrayal."},
    {"name": "Zuben Alschemali", "ra": "15h 17m 00s", "dec": "-09° 22' 58\"", "meaning": "Good fortune, high ambition, and social success (The 'North Scale')."},
    {"name": "Unukalhai", "ra": "15h 44m 16s", "dec": "+06° 25' 32\"", "meaning": "Passionate nature, violence, but potential for medical or healing skill."},
    {"name": "Agena", "ra": "14h 03m 49s", "dec": "-60° 22' 23\"", "meaning": "Position, friendship, refinement, and good health."},
    {"name": "Bungula", "ra": "14h 39m 36s", "dec": "-60° 50' 02\"", "meaning": "Beneficence, honors, and strong emotional ties."},

    # Sagittarius
    {"name": "Kornephoros", "ra": "16h 30m 13s", "dec": "+21° 29' 22\"", "meaning": "Fixedness of purpose, strength of character, and intellectual integrity."},
    {"name": "Yed Prior", "ra": "17h 10m 23s", "dec": "-03° 41' 33\"", "meaning": "Success in business, but potential for conflict or public struggle."},
    {"name": "Marfik", "ra": "16h 43m 08s", "dec": "+01° 59' 11\"", "meaning": "Passionate nature, keen intellect, and ability to influence others."},
    {"name": "Antares", "ra": "16h 29m 24s", "dec": "-26° 25' 55\"", "meaning": "Great honor, strategic mind, and courage, but danger of sudden loss or rashness."},
    {"name": "Rastaban", "ra": "17h 30m 26s", "dec": "+52° 18' 05\"", "meaning": "Impulsiveness, honor through risk, and potential for accidents."},
    {"name": "Sabik", "ra": "17h 10m 19s", "dec": "-15° 43' 30\"", "meaning": "Wastefulness, potential for moral struggle, but great intellectual brilliance."},
    {"name": "Atria", "ra": "16h 48m 40s", "dec": "-69° 01' 40\"", "meaning": "Just nature, love of architecture/structure, and enduring legacy."},
    {"name": "Lesath", "ra": "17h 30m 46s", "dec": "-37° 17' 45\"", "meaning": "Sharp intellect, incisive wit, but potential for danger or poison (The Stinger)."},
    {"name": "Etamin", "ra": "17h 56m 36s", "dec": "+51° 29' 20\"", "meaning": "Solitary nature, mental concentration, and interest in philosophy."},

    # CAPRICORN
    {"name": "Spiculum", "ra": "18h 05m 13s", "dec": "-23° 02' 52\"", "meaning": "Sharp intellect, but potential for eye problems or sudden blindness."},
    {"name": "Alnasl", "ra": "18h 05m 48s", "dec": "-30° 25' 25\"", "meaning": "Strong sense of direction, leadership, and ability to hit the mark."},
    {"name": "Polis", "ra": "18h 13m 47s", "dec": "-21° 03' 33\"", "meaning": "High ambition, success in leadership, and keen spiritual perception."},
    {"name": "Kaus Borealis", "ra": "18h 27m 58s", "dec": "-25° 25' 18\"", "meaning": "Idealistic leadership, justice, and mental flexibility."},
    {"name": "Facies", "ra": "18h 31m 40s", "dec": "-23° 53' 15\"", "meaning": "Intense focus, driven nature, but potential for harshness or violence."},
    {"name": "Vega", "ra": "18h 36m 56s", "dec": "+38° 47' 01\"", "meaning": "Great fortune, artistic talent, refinement, and hopeful nature."},
    {"name": "Sheliak", "ra": "18h 50m 05s", "dec": "+33° 21' 46\"", "meaning": "Artistic expression, musical talent, but potential for scandal."},
    {"name": "Dheneb", "ra": "19h 05m 25s", "dec": "+13° 51' 48\"", "meaning": "Success in martial affairs, command, and charitable power."},
    {"name": "Peacock", "ra": "20h 25m 39s", "dec": "-56° 44' 06\"", "meaning": "Vanity, love of display, but potential for high public office."},
    {"name": "Terebellum", "ra": "19h 52m 58s", "dec": "-26° 17' 39\"", "meaning": "Good fortune, success in commerce, and quiet strength."},

    # AQUARIUS 
    {"name": "Tarazed", "ra": "19h 43m 58s", "dec": "+10° 36' 40\"", "meaning": "Great imagination, strong will, and potential for clairvoyance."},
    {"name": "Sham", "ra": "19h 47m 23s", "dec": "+18° 05' 31\"", "meaning": "Combativeness, creative power, and sharp intellect."},
    {"name": "Albireo", "ra": "19h 30m 43s", "dec": "+27° 57' 35\"", "meaning": "Contemplative nature, artistic talent, and pleasant appearance."},
    {"name": "Altair", "ra": "19h 50m 47s", "dec": "+08° 52' 06\"", "meaning": "Boldness, courage, sudden but ephemeral wealth, and command."},
    {"name": "Algedi", "ra": "20h 18m 03s", "dec": "-12° 32' 41\"", "meaning": "Beneficence, sacrificial nature, and spiritual focus."},
    {"name": "Bos", "ra": "21h 05m 57s", "dec": "-11° 21' 47\"", "meaning": "Keen intellect, business ability, and analytical mind."},
    {"name": "Albali", "ra": "20h 52m 39s", "dec": "-09° 24' 57\"", "meaning": "Good fortune, social success, and helpfulness to others."},
    {"name": "Castra", "ra": "21h 44m 31s", "dec": "-18° 15' 12\"", "meaning": "Destructive influence, potential for sudden bad temper or injury."},
    {"name": "Nashira", "ra": "21h 39m 23s", "dec": "-16° 39' 53\"", "meaning": "Success in writing or government, overcoming evil through goodness."},
    {"name": "Kitalpha", "ra": "21h 15m 49s", "dec": "+05° 14' 52\"", "meaning": "Love of horses, swiftness in thought, and social grace."},
    {"name": "Sadalsuud", "ra": "21h 31m 33s", "dec": "-05° 34' 16\"", "meaning": "Great fortune, prosperity in business, and far-reaching influence."},
    {"name": "Gienah", "ra": "20h 54m 24s", "dec": "+33° 58' 13\"", "meaning": "Creative spirit, love of freedom, and success through detachment."},

    # PISCES
    {"name": "Fomalhaut", "ra": "22h 57m 39s", "dec": "-29° 37' 20\"", "meaning": "Success in creative or spiritual fields, transition from material to spiritual, but requires pure motives."},
    {"name": "Deneb Adige", "ra": "20h 41m 26s", "dec": "+45° 16' 49\"", "meaning": "Brilliant intellect, quick learning, and success in arts and sciences."},
    {"name": "Skat", "ra": "22h 54m 39s", "dec": "-15° 49' 15\"", "meaning": "Good fortune, lasting happiness, and helpfulness from others."},
    {"name": "Achernar", "ra": "01h 37m 43s", "dec": "-57° 14' 12\"", "meaning": "High office in religion or government, philosophical success, and sudden benefits."},
    {"name": "Markab", "ra": "23h 04m 46s", "dec": "+15° 12' 19\"", "meaning": "Ambition, great mental power, and success in legal or military affairs, but danger from fire/sharp objects."},
    {"name": "Scheat", "ra": "23h 03m 46s", "dec": "+28° 04' 58\"", "meaning": "Extremely high intellect, literary or poetic talent, but associated with sudden tragedy or floods."},
]